# Generated by Django 5.0.4 on 2024-06-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_blog', '0003_alter_post_contenido_alter_post_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=models.TextField(),
        ),
    ]
