# Generated by Django 5.0.4 on 2024-06-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_areas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/especialidad'),
        ),
    ]
