# Generated by Django 5.0.4 on 2024-07-01 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Area', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='created',
        ),
        migrations.RemoveField(
            model_name='area',
            name='update',
        ),
    ]
